// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBEUx-rc9RMKOMHwaMUNdoeLlNEDDnVk',
    appId: '1:57042941964:web:8cfe6d6effc95de62b1629',
    messagingSenderId: '57042941964',
    projectId: 'inschedule-e9cd0',
    authDomain: 'inschedule-e9cd0.firebaseapp.com',
    databaseURL: 'https://inschedule-e9cd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inschedule-e9cd0.firebasestorage.app',
    measurementId: 'G-Z4SQ7BK73W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JjxEIEmAE7TMGes-KD5eT5B-44nVoq4',
    appId: '1:57042941964:android:d7bc4dda105a2d4a2b1629',
    messagingSenderId: '57042941964',
    projectId: 'inschedule-e9cd0',
    databaseURL: 'https://inschedule-e9cd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inschedule-e9cd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3H_-HhJWQU76jwBTf6v-TXuTLm9XXdek',
    appId: '1:57042941964:ios:fa24665e076b95452b1629',
    messagingSenderId: '57042941964',
    projectId: 'inschedule-e9cd0',
    databaseURL: 'https://inschedule-e9cd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inschedule-e9cd0.firebasestorage.app',
    iosBundleId: 'com.example.inschedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3H_-HhJWQU76jwBTf6v-TXuTLm9XXdek',
    appId: '1:57042941964:ios:fa24665e076b95452b1629',
    messagingSenderId: '57042941964',
    projectId: 'inschedule-e9cd0',
    databaseURL: 'https://inschedule-e9cd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inschedule-e9cd0.firebasestorage.app',
    iosBundleId: 'com.example.inschedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWBEUx-rc9RMKOMHwaMUNdoeLlNEDDnVk',
    appId: '1:57042941964:web:070f2f4938bb0f562b1629',
    messagingSenderId: '57042941964',
    projectId: 'inschedule-e9cd0',
    authDomain: 'inschedule-e9cd0.firebaseapp.com',
    databaseURL: 'https://inschedule-e9cd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inschedule-e9cd0.firebasestorage.app',
    measurementId: 'G-1NKQT3WMWS',
  );

}